update dm
akonoroshi/datasets_turntaking pull request #2
Opened 2022-12-05 22:54 UTC by Shun-Tomita

2022-12-05 23:32 UTC, akonoroshi requested changes

2022-12-05 23:32 UTC, akonoroshi commented on datasets_turntaking/dialog_text_dm_rev2.py
> +class ConversationalDM(pl.LightningDataModule):
同じクラス名が別のところにあるので、混乱を避けるためにConversationalDM2に戻すか、デフォルトのデータセットでも問題なく動く（ビデオデータとの兼ね合いでおそらく無理そうだが？）ならこのファイルを消してdialog_text_dm.pyを上書きしてください。

2022-12-05 23:32 UTC, akonoroshi commented on datasets_turntaking/dialog_text_dm_rev2.py
> +            "--datasets", type=str, nargs="+", default=ConversationalDM.DATASETS
元のデータで動かないのであれば`default=["ami"]` にしてください

2022-12-05 23:37 UTC, akonoroshi requested changes
Collate_fnで画像データを返していないようですが？

2022-12-05 23:57 UTC, Shun-Tomita commented
@akonoroshi updated! 新しくpushしたもの確認できます？

2022-12-06 01:20 UTC, akonoroshi approved these changes
多分大丈夫だと思います！

2022-12-06 01:20 UTC, merged